### ISSUE TITLE
[Bug] Trying to generate dd from the mill submenu results in a runtime error.

### ISSUE THREAD

**Issue by Spockrates** [DidierRLopes/GamestonkTerminal#135]
**Describe the bug**
Trying to generate dd from the mill submenu results in a runtime error.

`(✨) (mill)> dd -t GME
Executing:   0%|                                                                                                 | 0/8 [00:00<?, ?cell/s]/usr/local/anaconda3/envs/gst/bin/python: No module named ipykernel_launcher
Executing:   0%|                                                                                                 | 0/8 [00:02<?, ?cell/s]
Traceback (most recent call last):
  File "terminal.py", line 208, in <module>
    main()
  File "terminal.py", line 126, in main
    b_quit = mill.papermill_menu()
  File "/Users/mitch/Gamestonk/GamestonkTerminal/gamestonk_terminal/papermill/papermill_menu.py", line 57, in papermill_menu
    due_diligence.analysis(l_args)
  File "/Users/mitch/Gamestonk/GamestonkTerminal/gamestonk_terminal/papermill/due_diligence.py", line 45, in analysis
    parameters=dict(ticker=s_ticker),
  File "/usr/local/anaconda3/envs/gst/lib/python3.6/site-packages/papermill/execute.py", line 114, in execute_notebook
    **engine_kwargs
  File "/usr/local/anaconda3/envs/gst/lib/python3.6/site-packages/papermill/engines.py", line 49, in execute_notebook_with_engine
    return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
  File "/usr/local/anaconda3/envs/gst/lib/python3.6/site-packages/papermill/engines.py", line 343, in execute_notebook
    cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
  File "/usr/local/anaconda3/envs/gst/lib/python3.6/site-packages/papermill/engines.py", line 402, in execute_managed_notebook
    return PapermillNotebookClient(nb_man, **final_kwargs).execute()
  File "/usr/local/anaconda3/envs/gst/lib/python3.6/site-packages/papermill/clientwrap.py", line 43, in execute
    with self.setup_kernel(**kwargs):
  File "/usr/local/anaconda3/envs/gst/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/anaconda3/envs/gst/lib/python3.6/site-packages/nbclient/client.py", line 452, in setup_kernel
    self.start_new_kernel_client()
  File "/usr/local/anaconda3/envs/gst/lib/python3.6/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/anaconda3/envs/gst/lib/python3.6/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/anaconda3/envs/gst/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/anaconda3/envs/gst/lib/python3.6/site-packages/nbclient/client.py", line 423, in async_start_new_kernel_client
    await ensure_async(self.kc.wait_for_ready(timeout=self.startup_timeout))
  File "/usr/local/anaconda3/envs/gst/lib/python3.6/site-packages/nbclient/util.py", line 85, in ensure_async
    result = await obj
  File "/usr/local/anaconda3/envs/gst/lib/python3.6/site-packages/jupyter_client/asynchronous/client.py", line 146, in wait_for_ready
    raise RuntimeError('Kernel died before replying to kernel_info')
RuntimeError: Kernel died before replying to kernel_info`

**Desktop (please complete the following information):**
 - OS: High Sierra 11.2.2
 - Python version 3.6.8

**Additional context**
Gamestonk installed via the most recent instructions (using poetry for requirement management)

**Comment by aia** [comment]
That means the notebook can't find your Jupyter kernel.

Do you have jupyter installed?

If not, could you try conda install jupyter in your environment?

**Comment by StokedKush** [comment]
> That means the notebook can't find your Jupyter kernel.
> 
> Do you have jupyter installed?
> 
> If not, could you try conda install jupyter in your environment?

 (mill)> dd -t TSLA
Executing:  62%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                  | 5/8 [00:02<00:01,  2.39cell/s]
Traceback (most recent call last):
  File "terminal.py", line 208, in <module>
    main()
  File "terminal.py", line 126, in main
    b_quit = mill.papermill_menu()
  File "C:\Users\Kushagra's Rig\GamestonkTerminal\gamestonk_terminal\papermill\papermill_menu.py", line 57, in papermill_menu
    due_diligence.analysis(l_args)
  File "C:\Users\Kushagra's Rig\GamestonkTerminal\gamestonk_terminal\papermill\due_diligence.py", line 45, in analysis
    parameters=dict(ticker=s_ticker),
  File "C:\ProgramData\Miniconda3\envs\gst\lib\site-packages\papermill\execute.py", line 118, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "C:\ProgramData\Miniconda3\envs\gst\lib\site-packages\papermill\execute.py", line 230, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError:
---------------------------------------------------------------------------
Exception encountered at "In [5]":
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-85eb4206edcd> in <module>
----> 1 import mplfinance as mpf
      2 from alpha_vantage.timeseries import TimeSeries
      3 ts = TimeSeries(key="REPLACE_ME", output_format="pandas")
      4 df_stock, _ = ts.get_daily_adjusted(symbol=ticker, outputsize="compact")
      5 df_stock.rename(columns = {'1. open':'Open', '2. high': 'High', '3. low':'Low', '4. close':'Close',

ModuleNotFoundError: No module named 'mplfinance'

I have installed the Jupyter and and Am getting this error

**Comment by aia** [comment]
yes, we need to add mplfinance to requirements.

For now

```
pip install mplfinance
```

**Comment by StokedKush** [comment]
> to

![image](https://user-images.githubusercontent.com/79958485/110427592-01fe6680-80ce-11eb-8c12-71b3b62a11c3.png)


That Worked !!! but that led me to this 

![image](https://user-images.githubusercontent.com/79958485/110427641-12aedc80-80ce-11eb-9fa5-b27721ce578d.png)

**Comment by aia** [comment]
Open another terminal window in the GamestonkTerminal directory and run

```
jupyter notebook
```

Or install https://github.com/nteract/nteract viewer and associate nteract with *.ipynb extensions.

**Comment by StokedKush** [comment]
> Open another terminal window in the GamestonkTerminal directory and run
> 
> ```
> jupyter notebook
> ```
> 
> Or install https://github.com/nteract/nteract viewer and associate nteract with *.ipynb extensions.

you are a lifesaver Dude. am now gonna update my Config APIs and test the rest of the features. Want to try Prediction command now

**Comment by aia** [comment]
> 
> 
> @aia in the config_terminal.py , I only have to replace "REPLACE_ME" only with "API CODE" ??

Or set an environment variable.

If you installed all additional ML modules and want to enable Prediction menu, you need to update ENABLE_PREDICT to True
