### ISSUE TITLE
No check if DataFrame is empty

### ISSUE THREAD

**Issue by lfdversluis** [DidierRLopes/GamestonkTerminal#178]
```
Traceback (most recent call last):
  File "terminal.py", line 223, in <module>
    main()
  File "terminal.py", line 123, in main
    s_ticker, (datetime.now() - timedelta(days=180)).strftime("%Y-%m-%d")
  File "C:\Users\L\Documents\GamestonkTerminal\gamestonk_terminal\main_helper.py", line 231, in candle
    df_stock = trend.load_ticker(s_ticker, s_start)
  File "C:\Users\L\Documents\GamestonkTerminal\gamestonk_terminal\fundamental_analysis\trendline_api.py", line 26, in load_ticker
    df_data = yf.download(ticker, start=start_date, progress=False)
  File "C:\Users\L\AppData\Roaming\Python\Python37\site-packages\yfinance\multi.py", line 127, in download
    keys=shared._DFS.keys())
  File "C:\Users\L\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\reshape\concat.py", line 284, in concat
    sort=sort,
  File "C:\Users\L\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\core\reshape\concat.py", line 331, in __init__
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
```

I ran  `candle abna` which I think might be a wrong stock symbol.

**Comment by DidierRLopes** [comment]
Thanks for pointing this out, #179 will fix this!

**Comment by DidierRLopes** [comment]
Closing this since #179 solves this
