### ISSUE TITLE
[Bug] ImportError: cannot import name 'API_FRED_KEY'

### ISSUE THREAD

**Issue by Deep-Six** [DidierRLopes/GamestonkTerminal#220]
**Describe the bug**
API_FRED_KEY is not defined:
Traceback (most recent call last):
  File "terminal.py", line 26, in <module>
    from gamestonk_terminal.fred import fred_menu as fm
  File "/home/jhenkel/src/personal/GamestonkTerminal/gamestonk_terminal/fred/fred_menu.py", line 7, in <module>
    from gamestonk_terminal.fred import fred_api
  File "/home/jhenkel/src/personal/GamestonkTerminal/gamestonk_terminal/fred/fred_api.py", line 12, in <module>
    from gamestonk_terminal.config_terminal import API_FRED_KEY
ImportError: cannot import name 'API_FRED_KEY'

**To Reproduce**
Follow the install instructions
python terminal.py

**Screenshots**

**Desktop (please complete the following information):**
- Arch Linux
 - Python version [e.g. 3.6.8]

**Additional context**
Add any other information that you think could be useful for us.

**Comment by Deep-Six** [comment]
Ignore, user error on config_terminal.py
