### ISSUE TITLE
[Bug] Crashes on tkinter.TclError

### ISSUE THREAD

**Issue by Twintop** [DidierRLopes/GamestonkTerminal#221]
**Describe the bug**
Attempting to run a command that will launch an external GUI will crash instead of erroring gracefully if tkinter is unable to connect to a display.

**To Reproduce**
1. Run these commands from CLI:
- `python terminal.py`
- `load GME`
- `view`
2. Crashes
(see full console at end)

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10/WSL2
 - Python version: 3.8.2

**Additional context**
I'm trying to get an X server working on Windows (new environment) and in doing so encountered this error.

Full console output:

```(gst) david@DESKTOP-EGUQI77:~/GamestonkTerminal$ python terminal.py

Welcome to Gamestonk Terminal 🚀

What do you want to do?
   help        help to see this menu again
   quit        to abandon the program

   clear       clear a specific stock ticker from analysis
   load        load a specific stock ticker for analysis
   candle      view a candle chart for a specific stock ticker
   view        view and load a specific stock ticker for technical analysis

Stock: ?
Market CLOSED.

Menus:
   disc        discover trending stocks,         e.g. map, sectors, high short interest
   mill        papermill menu,                   menu to generate notebook reports
   sen         sentiment of the market,          from: reddit, stocktwits, twitter
   fred        economic data,                    from: Federal Reserve Bank of St. Louis

(✨)> load GME
Loading Daily GME stock for analysis.

(✨)> view
Traceback (most recent call last):
  File "terminal.py", line 255, in <module>
    main()
  File "terminal.py", line 149, in main
    view(l_args, s_ticker, s_start, s_interval, df_stock)
  File "/home/david/GamestonkTerminal/gamestonk_terminal/main_helper.py", line 404, in view
    plot_view_stock(df_stock.iloc[:, ln_col_idx], ns_parser.s_ticker)
  File "/home/david/GamestonkTerminal/gamestonk_terminal/helper_funcs.py", line 44, in plot_view_stock
    _, axVolume = plt.subplots(figsize=plot_autoscale(), dpi=cfgPlot.PLOT_DPI)
  File "/home/david/anaconda3/envs/gst/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 451, in wrapper
    return func(*args, **kwargs)
  File "/home/david/anaconda3/envs/gst/lib/python3.8/site-packages/matplotlib/pyplot.py", line 1287, in subplots
    fig = figure(**fig_kw)
  File "/home/david/anaconda3/envs/gst/lib/python3.8/site-packages/matplotlib/pyplot.py", line 687, in figure
    figManager = new_figure_manager(num, figsize=figsize,
  File "/home/david/anaconda3/envs/gst/lib/python3.8/site-packages/matplotlib/pyplot.py", line 315, in new_figure_manager
    return _backend_mod.new_figure_manager(*args, **kwargs)
  File "/home/david/anaconda3/envs/gst/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 3494, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/home/david/anaconda3/envs/gst/lib/python3.8/site-packages/matplotlib/backends/_backend_tk.py", line 885, in new_figure_manager_given_figure
    window = tk.Tk(className="matplotlib")
  File "/home/david/anaconda3/envs/gst/lib/python3.8/tkinter/__init__.py", line 2270, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "192.168.0.1:0"
(gst) david@DESKTOP-EGUQI77:~/GamestonkTerminal$```

**Comment by aia** [comment]
When you run view, the program opens a window. Your WSL2 is not connected to your Windows UI, so the window fails to open.

This behavior is expected.

On Windows, you want to run the terminal outside of WSL/WSL2.

If you really really desire to run the terminal in WSL, you need to start an X server on your windows and do a correct DISPLAY export in your WSL shell.

**Comment by Twintop** [comment]
I don't doubt that the behavior is expected, I'm raising it as a bug because the user experience is poor. Rather than crashing out in this instance it would be preferred to have a message like "Could not connect to display. Check your settings." and continue operating.

**Comment by aia** [comment]
That is true.
