### ISSUE TITLE
Pred module not working on window 10 [Bug]

### ISSUE THREAD

**Issue by sabirjana** [DidierRLopes/GamestonkTerminal#226]
**Describe the bug**
I have windows 10 system and facing the following issue when I try to run 'pred'

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior

**Screenshots**
`2021-03-18 21:15:35.987033: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-03-18 21:15:35.987903: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.10.5, library is 1.10.6
        SUMMARY OF THE HDF5 CONFIGURATION
        =================================

General Information:
-------------------
                   HDF5 Version: 1.10.6
                  Configured on: 2021-01-08
                  Configured by: Ninja
                    Host system: Windows-10.0.14393
              Uname information: Windows
                       Byte sex: little-endian
             Installation point: D:/bld/hdf5_split_1610146300400/_h_env/Library

Compiling Options:
------------------
                     Build Mode: RELEASE
              Debugging Symbols: OFF
                        Asserts: OFF
                      Profiling: OFF
             Optimization Level: OFF

Linking Options:
----------------
                      Libraries:
  Statically Linked Executables: OFF
                        LDFLAGS: /machine:x64
                     H5_LDFLAGS:
                     AM_LDFLAGS:
                Extra libraries: D:/bld/hdf5_split_1610146300400/_h_env/Library/lib/libcurl.lib;D:/bld/hdf5_split_1610146300400/_h_env/Library/lib/libssl.lib;D:/bld/hdf5_split_1610146300400/_h_env/Library/lib/libcrypto.lib
                       Archiver: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/lib.exe
                         Ranlib:

Languages:
----------
                              C: YES
                     C Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe 19.16.27045.0
                       CPPFLAGS:
                    H5_CPPFLAGS:
                    AM_CPPFLAGS:
                         CFLAGS:  /DWIN32 /D_WINDOWS /W3
                      H5_CFLAGS:
                      AM_CFLAGS:
               Shared C Library: YES
               Static C Library: YES

                        Fortran: OFF
               Fortran Compiler:
                  Fortran Flags:
               H5 Fortran Flags:
               AM Fortran Flags:
         Shared Fortran Library: YES
         Static Fortran Library: YES

                            C++: ON
                   C++ Compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe 19.16.27045.0
                      C++ Flags: -LTCG  /DWIN32 /D_WINDOWS /W3 /GR /EHsc
                   H5 C++ Flags:
                   AM C++ Flags:
             Shared C++ Library: YES
             Static C++ Library: YES

                            JAVA: OFF
                 JAVA Compiler:

'Features:
---------
                   Parallel HDF5: OFF
Parallel Filtered Dataset Writes:
              Large Parallel I/O:
              High-level library: ON
                Build HDF5 Tests: ON
                Build HDF5 Tools: ON
                    Threadsafety: ON
             Default API mapping: v110
  With deprecated public symbols: ON
          I/O filters (external):  DEFLATE
                             MPE:
                      Direct VFD:
              (Read-Only) S3 VFD: 1
            (Read-Only) HDFS VFD:
                         dmalloc:
  Packages w/ extra debug output:
                     API Tracing: OFF
            Using memory checker: OFF
 Memory allocation sanity checks: OFF
          Function Stack Tracing: OFF
       Strict File Format Checks: OFF
    Optimization Instrumentation:
Bye...

(gst) 
**Desktop (please complete the following information):**
 - OS: Window 10
 - Python version: 3.6.8

**Additional context**
Add any other information that you think could be useful for us.

**Comment by DidierRLopes** [comment]
Hey,

I'm not familiar with this issue. @arcutright have you come across this before?

**Comment by sabirjana** [comment]
I tried on 2 different machine and ended up with same issue. In both case poetry was not able to install fbprophet so I used conda-forge to install fbprophet 0.6

**Comment by arcutright** [comment]
Hmm, I also get this issue after pulling from main. Checking out feature/pred-xla-refactor and using python=3.6.8, it works for me. I will try to investigate where this is coming from.

**Comment by arcutright** [comment]
You can fix this by force-installing the expected hdf5
```
conda install -c conda-forge hdf5=1.10.5
```

@DidierRLopes: 
Not sure how we can add this constraint to poetry because it keeps giving me `Could not find a matching version of package hdf5`. Also not sure why the commit mentioned above led to this change.

**Comment by sabirjana** [comment]
Thank you for your prompt response!! I will try this and update accordingly.

**Comment by djedu** [comment]
I came across the exact same issue on a Win10 machine running python 3.6.8.

Not sure if this helps, but managed to partially solve by switching to Python 3.7 (fbprophet was causing dependency issues on 3.6.8). I installed all dependencies with poetry, and all pred tools worked except fbprophet.

Unfortunately I've gone down a rabbit hole of trying tensorflow-gpu for CUDA acceleration and have lost the hours I spent getting it working so won't be able to check anything but I'll try to help...

**Comment by sabirjana** [comment]
It worked!! after setting up env with python 3.7 and installing fbprophet==0.6 using conda-forge and hdf5==1.10.5 however faced issues with rnn and lstm
` (pred)> rnn
Cannot convert a symbolic Tensor (simple_rnn/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported
Traceback (most recent call last):
  File "C:\Users\sabir\OneDrive\Desktop\Sabir\python\GamestonkTerminal\gamestonk_terminal\prediction_techniques\neural_networks.py", line 608, in rnn
    cfg_nn_models.Recurrent_Neural_Network, ns_parser.n_inputs, ns_parser.n_days
  File "C:\Users\sabir\OneDrive\Desktop\Sabir\python\GamestonkTerminal\gamestonk_terminal\prediction_techniques\neural_networks.py", line 55, in build_neural_network_model
    model.add(SimpleRNN(**d_layer["SimpleRNN"], input_shape=(n_inputs, 1)))
  File "C:\Users\sabir\anaconda3\envs\gst\lib\site-packages\tensorflow\python\training\tracking\base.py", line 517, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\sabir\anaconda3\envs\gst\lib\site-packages\tensorflow\python\keras\engine\sequential.py", line 208, in add
    layer(x)
  File "C:\Users\sabir\anaconda3\envs\gst\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 660, in __call__
    return super(RNN, self).__call__(inputs, **kwargs)
  File "C:\Users\sabir\anaconda3\envs\gst\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 952, in __call__
    input_list)
  File "C:\Users\sabir\anaconda3\envs\gst\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1091, in _functional_construction_call
    inputs, input_masks, args, kwargs)
  File "C:\Users\sabir\anaconda3\envs\gst\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 822, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "C:\Users\sabir\anaconda3\envs\gst\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 863, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "C:\Users\sabir\anaconda3\envs\gst\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 1573, in call
    inputs, mask=mask, training=training, initial_state=initial_state)
  File "C:\Users\sabir\anaconda3\envs\gst\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 732, in call
    inputs, initial_state, constants)
  File "C:\Users\sabir\anaconda3\envs\gst\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 859, in _process_inputs
    initial_state = self.get_initial_state(inputs)
  File "C:\Users\sabir\anaconda3\envs\gst\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 643, in get_initial_state
    inputs=None, batch_size=batch_size, dtype=dtype)
  File "C:\Users\sabir\anaconda3\envs\gst\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 1385, in get_initial_state
    return _generate_zero_filled_state_for_cell(self, inputs, batch_size, dtype)
  File "C:\Users\sabir\anaconda3\envs\gst\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 2987, in _generate_zero_filled_state_for_cell
    return _generate_zero_filled_state(batch_size, cell.state_size, dtype)
  File "C:\Users\sabir\anaconda3\envs\gst\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 3005, in _generate_zero_filled_state
    return create_zeros(state_size)
  File "C:\Users\sabir\anaconda3\envs\gst\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 3000, in create_zeros
    return array_ops.zeros(init_state_size, dtype=dtype)
  File "C:\Users\sabir\anaconda3\envs\gst\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\sabir\anaconda3\envs\gst\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2819, in wrapped
    tensor = fun(*args, **kwargs)
  File "C:\Users\sabir\anaconda3\envs\gst\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2868, in zeros
    output = _constant_if_small(zero, shape, dtype, name)
  File "C:\Users\sabir\anaconda3\envs\gst\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2804, in _constant_if_small
    if np.prod(shape) < 1000:
  File "<__array_function__ internals>", line 6, in prod
  File "C:\Users\sabir\anaconda3\envs\gst\lib\site-packages\numpy\core\fromnumeric.py", line 3031, in prod
    keepdims=keepdims, initial=initial, where=where)
  File "C:\Users\sabir\anaconda3\envs\gst\lib\site-packages\numpy\core\fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
  File "C:\Users\sabir\anaconda3\envs\gst\lib\site-packages\tensorflow\python\framework\ops.py", line 855, in __array__
    " a NumPy call, which is not supported".format(self.name))
NotImplementedError: Cannot convert a symbolic Tensor (simple_rnn/strided_slice:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported`

**Comment by arcutright** [comment]
This is a different issue related to python>=3.7, see #236. I managed to get python=3.8.8 working for gst there.

**Comment by sabirjana** [comment]
So are you suggesting to have python 3.8.8 env and everything should work?

**Comment by DidierRLopes** [comment]
Will close this based on @arcutright's PR. Have a look at #236 or the updated README install process
