### ISSUE TITLE
[Bug] Unhandled Error when closing candle graph

### ISSUE THREAD

**Issue by brunottonurb** [DidierRLopes/GamestonkTerminal#299]
**Describe the bug**
When closing the candle graph with q or esc keys or by clicking to close, the application crashes.

**To Reproduce**
Use Ubuntu 20.04, start GST, `load IFNNY`, `candle`

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Python version 3.8.8/3.6.8
 - AMD Ryzen 4750u

**Additional context**
```
> load IFNNY
Loading Daily IFNNY stock with starting period 2015-01-01 for analysis.

> candle

> Traceback (most recent call last):
  File "terminal.py", line 309, in <module>
    main()
  File "terminal.py", line 119, in main
    as_input = session.prompt(f"{get_flair()}> ", completer=completer)
  File "/home/USERNAME/anaconda3/envs/gst/lib/python3.8/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1013, in prompt
    return self.app.run(set_exception_handler=set_exception_handler)
  File "/home/USERNAME/anaconda3/envs/gst/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 848, in run
    return loop.run_until_complete(
  File "/home/USERNAME/anaconda3/envs/gst/lib/python3.8/asyncio/base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "/home/USERNAME/anaconda3/envs/gst/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/home/USERNAME/anaconda3/envs/gst/lib/python3.8/asyncio/base_events.py", line 1823, in _run_once
    event_list = self._selector.select(timeout)
  File "/home/USERNAME/anaconda3/envs/gst/lib/python3.8/site-packages/prompt_toolkit/eventloop/inputhook.py", line 117, in select
    self.inputhook(InputHookContext(self._r, input_is_ready))
  File "/home/USERNAME/Code/GamestonkTerminal/gamestonk_terminal/menu.py", line 12, in inputhook
    pyplot.pause(0.1)
  File "/home/USERNAME/anaconda3/envs/gst/lib/python3.8/site-packages/matplotlib/pyplot.py", line 313, in pause
    canvas.start_event_loop(interval)
  File "/home/USERNAME/anaconda3/envs/gst/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2309, in start_event_loop
    self.flush_events()
  File "/home/USERNAME/anaconda3/envs/gst/lib/python3.8/site-packages/matplotlib/backends/_backend_tk.py", line 405, in flush_events
    self._master.update()
  File "/home/USERNAME/anaconda3/envs/gst/lib/python3.8/tkinter/__init__.py", line 1314, in update
    self.tk.call('update')
_tkinter.TclError: can't invoke "update" command: application has been destroyed
```

**Comment by aia** [comment]
Does this help?

https://github.com/DidierRLopes/GamestonkTerminal/pull/300

**Comment by brunottonurb** [comment]
#300 fixes it!
