### ISSUE TITLE
Install issue - required packages installation

### ISSUE THREAD

**Issue by hubertdepsv** [DidierRLopes/GamestonkTerminal#302]
As requested in the read me if having an issue with importing statsmodel (and actually other packages):

(gst) C:\Users\hp98\GamestonkTerminal>python terminal.py
Traceback (most recent call last):
  File "terminal.py", line 30, in <module>
    from gamestonk_terminal.residuals_analysis import ra_controller
  File "C:\Users\hp98\GamestonkTerminal\gamestonk_terminal\residuals_analysis\ra_controller.py", line 10, in <module>
    from gamestonk_terminal.residuals_analysis import residuals_model
  File "C:\Users\hp98\GamestonkTerminal\gamestonk_terminal\residuals_analysis\residuals_model.py", line 7, in <module>
    import pmdarima
ModuleNotFoundError: No module named 'pmdarima'
-> solved using conda install -c saravji pmdarima

(gst) C:\Users\hp98\GamestonkTerminal>python terminal.py
Traceback (most recent call last):
  File "terminal.py", line 27, in <module>
    from gamestonk_terminal.exploratory_data_analysis import eda_controller
  File "C:\Users\hp98\GamestonkTerminal\gamestonk_terminal\exploratory_data_analysis\eda_controller.py", line 9, in <module>
    from gamestonk_terminal.exploratory_data_analysis import eda_api
  File "C:\Users\hp98\GamestonkTerminal\gamestonk_terminal\exploratory_data_analysis\eda_api.py", line 13, in <module>
    import statsmodels.api as sm
ModuleNotFoundError: No module named 'statsmodels'

-> solved using `conda install statsmodel`

Now I have this problem with sklearn's six:

(gst) C:\Users\hp98\GamestonkTerminal>python terminal.py
Traceback (most recent call last):
  File "terminal.py", line 30, in <module>
    from gamestonk_terminal.residuals_analysis import ra_controller
  File "C:\Users\hp98\GamestonkTerminal\gamestonk_terminal\residuals_analysis\ra_controller.py", line 10, in <module>
    from gamestonk_terminal.residuals_analysis import residuals_model
  File "C:\Users\hp98\GamestonkTerminal\gamestonk_terminal\residuals_analysis\residuals_model.py", line 7, in <module>
    import pmdarima
  File "C:\Users\hp98\anaconda3\envs\gst\lib\site-packages\pmdarima\__init__.py", line 29, in <module>
    from .arima import auto_arima, ARIMA, AutoARIMA
  File "C:\Users\hp98\anaconda3\envs\gst\lib\site-packages\pmdarima\arima\__init__.py", line 5, in <module>
    from .approx import *
  File "C:\Users\hp98\anaconda3\envs\gst\lib\site-packages\pmdarima\arima\approx.py", line 12, in <module>
    from ..utils.array import c
  File "C:\Users\hp98\anaconda3\envs\gst\lib\site-packages\pmdarima\utils\__init__.py", line 5, in <module>
    from .array import *
  File "C:\Users\hp98\anaconda3\envs\gst\lib\site-packages\pmdarima\utils\array.py", line 10, in <module>
    from sklearn.externals import six
ImportError: cannot import name 'six'

**Comment by jmaslek** [comment]
So I found an issue in pmdarima (https://github.com/alkaline-ml/pmdarima/issues/375) and I also see you did conda install for that.

In order to install properly you should use pip install not conda install.

Let me know if that works. If not, just try pip installing requirements.txt.

**Comment by hubertdepsv** [comment]
Hi!
Thanks for your answer!

Why should I use pip instead of conda?

I tried to uninstall both statsmodels and pmdarima to reinstall them with pip - uninstalling statsmodels worked but when trying to reinstall it I got an error and uninstalling pmdarima did not even work.

I'm going to remove the whole virtual environment to try everything again.

**Comment by jmaslek** [comment]
> Why should I use pip instead of conda?

At least for the pmdarima (as mentioned in the thread I referenced above) -- someone else put the package on conda, so it is not up to date.  Their official one is through pypi (pip).  So that is why they say to use pip.

> I'm going to remove the whole virtual environment to try everything again.

I have found that using `poetry install` just gives the easiest install
