### ISSUE TITLE
[Bug] pyportfolioopt dependency cvxpy breaks numpy 1.19

### ISSUE THREAD

**Issue by sabirjana** [DidierRLopes/GamestonkTerminal#348]
**Describe the bug**
I updated the terminal and it stopped working. 

**To Reproduce**
Steps(from the start) and commands to reproduce the behavior

**Screenshots**
```
'(gst-env)'D:\P4Finance\GamestonkTerminal>python terminal.py
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "terminal.py", line 26, in <module>
    from gamestonk_terminal.comparison_analysis import ca_controller
  File "D:\P4Finance\GamestonkTerminal\gamestonk_terminal\comparison_analysis\ca_controller.py", line 19, in <module>
    from gamestonk_terminal.portfolio_optimization import po_controller
  File "D:\P4Finance\GamestonkTerminal\gamestonk_terminal\portfolio_optimization\po_controller.py", line 12, in <module>
    from gamestonk_terminal.portfolio_optimization import optimizer_view as po_api
  File "D:\P4Finance\GamestonkTerminal\gamestonk_terminal\portfolio_optimization\optimizer_view.py", line 9, in <module>
    from pypfopt import plotting
  File "D:\P4Finance\gst-env\lib\site-packages\pypfopt\__init__.py", line 1, in <module>
    from .black_litterman import (
  File "D:\P4Finance\gst-env\lib\site-packages\pypfopt\black_litterman.py", line 13, in <module>
    from . import base_optimizer
  File "D:\P4Finance\gst-env\lib\site-packages\pypfopt\base_optimizer.py", line 14, in <module>
    import cvxpy as cp
  File "D:\P4Finance\gst-env\lib\site-packages\cvxpy\__init__.py", line 18, in <module>
    from cvxpy.atoms import *
  File "D:\P4Finance\gst-env\lib\site-packages\cvxpy\atoms\__init__.py", line 20, in <module>
    from cvxpy.atoms.geo_mean import geo_mean
  File "D:\P4Finance\gst-env\lib\site-packages\cvxpy\atoms\geo_mean.py", line 20, in <module>
    from cvxpy.utilities.power_tools import (fracify, decompose, approx_error, lower_bound,
  File "D:\P4Finance\gst-env\lib\site-packages\cvxpy\utilities\power_tools.py", line 18, in <module>
    from cvxpy.atoms.affine.reshape import reshape
  File "D:\P4Finance\gst-env\lib\site-packages\cvxpy\atoms\affine\reshape.py", line 18, in <module>
    from cvxpy.atoms.affine.hstack import hstack
  File "D:\P4Finance\gst-env\lib\site-packages\cvxpy\atoms\affine\hstack.py", line 18, in <module>
    from cvxpy.atoms.affine.affine_atom import AffAtom
  File "D:\P4Finance\gst-env\lib\site-packages\cvxpy\atoms\affine\affine_atom.py", line 22, in <module>
    from cvxpy.cvxcore.python import canonInterface
  File "D:\P4Finance\gst-env\lib\site-packages\cvxpy\cvxcore\python\__init__.py", line 3, in <module>
    import _cvxcore
ImportError: numpy.core.multiarray failed to import
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python 3.8

**Additional context**
Add any other information that you think could be useful for us.

**Comment by jmaslek** [comment]
Does pip install -U numpy fix it?

**Comment by aia** [comment]
This is the following issue: https://github.com/cvxgrp/cvxpy/issues/1229

We need to downgrade the pyportfolioopt to get to cvxpy version 1.1.7. 

cvxpy 1.1.7 is the last version that supports numpy 1.19.

In the mean time

```
pip uninstall cvxpy
pip install cvxpy==1.1.7
```

**Comment by aia** [comment]
CI gets the same error - https://github.com/DidierRLopes/GamestonkTerminal/pull/371/checks?check_run_id=2385831398

**Comment by aia** [comment]
cvxpy is a terrible library from what I am seeing

**Comment by jmaslek** [comment]
I am in the process of doing custom optimizations and I think I can do that in scipy.  So I can try to remove that dependency in the next week or so.

**Comment by aia** [comment]
I use straight scipy too. Understanding of your returns, adjustments and constraints is far more important than an optimizer.

**Comment by aia** [comment]
```
conda install -c conda-forge cvxpy
```
is the solution

**Comment by aia** [comment]
Oh, and if you are on Windows and not on conda - get on conda.
