### ISSUE TITLE
ModuleNotFoundError: No module named 'flair'

### ISSUE THREAD

**Issue by Pranav4399** [DidierRLopes/GamestonkTerminal#46]
I followed this guide  https://imgur.com/a/gqgVJPn to setup the terminal in anaconda environment but I'm getting the flair module error even though that is already installed along with pytorch. Can someone clarify me on this about what I should do ?

This is the complete error I'm getting - 

warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Traceback (most recent call last):
  File "D:\rPython\GamestonkTerminal\gamestonk_terminal.py", line 11, in <module>
    from sentiment import sen_menu as sm
  File "D:\rPython\GamestonkTerminal\sentiment\sen_menu.py", line 5, in <module>
    from sentiment import twitter_api
  File "D:\rPython\GamestonkTerminal\sentiment\twitter_api.py", line 5, in <module>
    import flair
ModuleNotFoundError: No module named 'flair'

**Comment by Pranav4399** [comment]
> 
> 
> I followed this guide https://imgur.com/a/gqgVJPn to setup the terminal in anaconda environment but I'm getting the flair module error even though that is already installed along with pytorch. Can someone clarify me on this about what I should do ?
> 
> This is the complete error I'm getting -
> 
> warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
> Traceback (most recent call last):
> File "D:\rPython\GamestonkTerminal\gamestonk_terminal.py", line 11, in
> from sentiment import sen_menu as sm
> File "D:\rPython\GamestonkTerminal\sentiment\sen_menu.py", line 5, in
> from sentiment import twitter_api
> File "D:\rPython\GamestonkTerminal\sentiment\twitter_api.py", line 5, in
> import flair
> ModuleNotFoundError: No module named 'flair'
