### ISSUE TITLE
Pystan install error on windows 3.6.8

### ISSUE THREAD

**Issue by StokedKush** [DidierRLopes/GamestonkTerminal#81]
Am new to coding and all and just want to try this Terminal as a Forex Trader

**Error 1**

_ERROR: Command errored out with exit status 1:
   command: 'c:\program files\python36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\KUSHAG~1\\AppData\\Local\\Temp\\pip-install-aqsn39k_\\fbprophet_7e073f007ad24dc38ebaceaed737ff87\\setup.py'"'"'; __file__='"'"'C:\\Users\\KUSHAG~1\\AppData\\Local\\Temp\\pip-install-aqsn39k_\\fbprophet_7e073f007ad24dc38ebaceaed737ff87\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\KUSHAG~1\AppData\Local\Temp\pip-wheel-o7rq_m_5'
       cwd: C:\Users\KUSHAG~1\AppData\Local\Temp\pip-install-aqsn39k_\fbprophet_7e073f007ad24dc38ebaceaed737ff87\
  Complete output (43 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\fbprophet
  creating build\lib\fbprophet\stan_model
  Importing plotly failed. Interactive plots will not work.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\KUSHAG~1\AppData\Local\Temp\pip-install-aqsn39k_\fbprophet_7e073f007ad24dc38ebaceaed737ff87\setup.py", line 148, in <module>
      """
    File "C:\Users\Kushagra's Rig\AppData\Roaming\Python\Python36\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "c:\program files\python36\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\program files\python36\lib\distutils\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "c:\program files\python36\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\Kushagra's Rig\AppData\Roaming\Python\Python36\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "c:\program files\python36\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\program files\python36\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "c:\program files\python36\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\program files\python36\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\program files\python36\lib\distutils\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\Users\KUSHAG~1\AppData\Local\Temp\pip-install-aqsn39k_\fbprophet_7e073f007ad24dc38ebaceaed737ff87\setup.py", line 48, in run
      build_models(target_dir)
    File "C:\Users\KUSHAG~1\AppData\Local\Temp\pip-install-aqsn39k_\fbprophet_7e073f007ad24dc38ebaceaed737ff87\setup.py", line 38, in build_models
      StanBackendEnum.get_backend_class(backend).build_model(target_dir, MODEL_DIR)
    File "C:\Users\KUSHAG~1\AppData\Local\Temp\pip-install-aqsn39k_\fbprophet_7e073f007ad24dc38ebaceaed737ff87\fbprophet\models.py", line 206, in build_model
      import pystan
    File "C:\Users\Kushagra's Rig\AppData\Roaming\Python\Python36\site-packages\pystan\__init__.py", line 9, in <module>
      from pystan.api import stanc, stan
    File "C:\Users\Kushagra's Rig\AppData\Roaming\Python\Python36\site-packages\pystan\api.py", line 13, in <module>
      import pystan._api  # stanc wrapper
  ImportError: DLL load failed: The specified module could not be found.
  ----------------------------------------
  ERROR: Failed building wheel for fbprophet_

**ERROR 2**

ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\KUSHAG~1\\AppData\\Local\\Temp\\pip-install-aqsn39k_\\fbprophet_7e073f007ad24dc38ebaceaed737ff87\\setup.py'"'"'; __file__='"'"'C:\\Users\\KUSHAG~1\\AppData\\Local\\Temp\\pip-install-aqsn39k_\\fbprophet_7e073f007ad24dc38ebaceaed737ff87\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\KUSHAG~1\AppData\Local\Temp\pip-record-k1dfbn65\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\program files\python36\Include\fbprophet'
         cwd: C:\Users\KUSHAG~1\AppData\Local\Temp\pip-install-aqsn39k_\fbprophet_7e073f007ad24dc38ebaceaed737ff87\
    Complete output (45 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib
    creating build\lib\fbprophet
    creating build\lib\fbprophet\stan_model
    Matplotlib is building the font cache; this may take a moment.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\KUSHAG~1\AppData\Local\Temp\pip-install-aqsn39k_\fbprophet_7e073f007ad24dc38ebaceaed737ff87\setup.py", line 148, in <module>
        """
      File "C:\Users\Kushagra's Rig\AppData\Roaming\Python\Python36\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "c:\program files\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\program files\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\program files\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Kushagra's Rig\AppData\Roaming\Python\Python36\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\program files\python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\program files\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\program files\python36\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\program files\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\KUSHAG~1\AppData\Local\Temp\pip-install-aqsn39k_\fbprophet_7e073f007ad24dc38ebaceaed737ff87\setup.py", line 48, in run
        build_models(target_dir)
      File "C:\Users\KUSHAG~1\AppData\Local\Temp\pip-install-aqsn39k_\fbprophet_7e073f007ad24dc38ebaceaed737ff87\setup.py", line 38, in build_models
        StanBackendEnum.get_backend_class(backend).build_model(target_dir, MODEL_DIR)
      File "C:\Users\KUSHAG~1\AppData\Local\Temp\pip-install-aqsn39k_\fbprophet_7e073f007ad24dc38ebaceaed737ff87\fbprophet\models.py", line 206, in build_model
        import pystan
      File "c:\program files\python36\lib\site-packages\pystan\__init__.py", line 9, in <module>
        from pystan.api import stanc, stan
      File "c:\program files\python36\lib\site-packages\pystan\api.py", line 14, in <module>
        import pystan._api  # stanc wrapper
    ImportError: DLL load failed: The specified module could not be found.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\KUSHAG~1\\AppData\\Local\\Temp\\pip-install-aqsn39k_\\fbprophet_7e073f007ad24dc38ebaceaed737ff87\\setup.py'"'"'; __file__='"'"'C:\\Users\\KUSHAG~1\\AppData\\Local\\Temp\\pip-install-aqsn39k_\\fbprophet_7e073f007ad24dc38ebaceaed737ff87\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\KUSHAG~1\AppData\Local\Temp\pip-record-k1dfbn65\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\program files\python36\Include\fbprophet' Check the logs for full command output.

**ERROR 3**

C:\Program Files\Python36\Lib\site-packages\GamestonkTerminal-main\GamestonkTerminal>python gamestonk_terminal.py
Traceback (most recent call last):
  File "gamestonk_terminal.py", line 7, in <module>
    from fundamental_analysis import fa_menu as fam
  File "C:\Program Files\Python36\Lib\site-packages\GamestonkTerminal-main\GamestonkTerminal\fundamental_analysis\fa_menu.py", line 2, in <module>
    from alpha_vantage.fundamentaldata import FundamentalData
ModuleNotFoundError: No module named 'alpha_vantage'

**Comment by shadycuz** [comment]
@StokedKush What is the output of `python --version`? 

We are also adding a docker option soon. I will let you know when we have that ready.

**Comment by StokedKush** [comment]
> @StokedKush What is the output of `python --version`?
> 
> We are also adding a docker option soon. I will let you know when we have that ready.

I am using python 3.6.8 as stated that this is tested on that version. Am really excited to use this terminal.

**Comment by shadycuz** [comment]
@StokedKush We have been testing against linux with python 3.6.13, 3.7 and 3.8. We still need to add testing for mac and windows. 

I can recommend you try 2 things. 

First try to install pystan on its own. `pip install pystan=2.18` . Then try to install GamestonkTerminal with `pip install -r requirements.txt`. 

If that doesn't work could you try to install python 3.8 instead?

**Comment by StokedKush** [comment]
> @StokedKush We have been testing against linux with python 3.6.13, 3.7 and 3.8. We still need to add testing for mac and windows.
> 
> I can recommend you try 2 things.
> 
> First try to install pystan on its own. `pip install pystan=2.18` . Then try to install GamestonkTerminal with `pip install -r requirements.txt`.
> 
> If that doesn't work could you try to install python 3.8 instead?

I see. It's working perfectly fine on Linux? Can I see some screenshots how does it looks.. I can try what you said on both versions and get back to you. 

Thanks ;)

**Comment by StokedKush** [comment]
I tried on both the versions and it says Failed to build fbprophet

**Comment by DidierRLopes** [comment]
Hey @StokedKush ,

Can you attempt to run this:
conda install -c conda-forge fbprophet -y

Let me know if it works

**Comment by StokedKush** [comment]
> Hey @StokedKush ,
> 
> Can you attempt to run this:
> conda install -c conda-forge fbprophet -y
> 
> Let me know if it works

I just installed the miniconda environment in my pc and the command that you just gave is working, Let's see.

**Comment by StokedKush** [comment]
![image](https://user-images.githubusercontent.com/79958485/109786778-89ae2600-7c33-11eb-9a03-f8d7f71ec885.png)

I removed pystan from requirements and I guess now it's installing, Pystan is creating some issues

**Comment by shadycuz** [comment]
@StokedKush I tried for a while yesterday to fix this. Thats when I discovered the version of `pystan` we need is not officially supported anymore on windows. You may be able to get it installed via conda but even that is hit and miss. 

Could you please try the docker container?

**Comment by shadycuz** [comment]
I'm going to close this now. Lots has changed since this was opened. You can run `git checkout main`, `git pull main` to fetch the latest and attempt to reinstall.

The project has been testest to work with Pythons 3.6.8, 3.7 and 3.8. Tensorflow doesn't support python 3.9 yet.

We are using poetry to manage the project and that is one option for installing. The other is to install with the requirements.txt. Feel free to use any virtual environment you want.

Just make sure to run pip install --upgrade pip as that was affecting some people as tensorflow requires pip >= 2.19 (or something like that).

We also have a dockerfile if you would prefer to use docker. We will also soon be offering an "official image" on dockerhub.

Oh and Windows is only supported with docker because pystan is not available for windows (officially).

If you are having problems please open a new issue =).

🚀 GamestonkTerminal 🌔
