### ISSUE TITLE
[Bug] Not being able to run from the docker image

### ISSUE THREAD

**Issue by efontan** [DidierRLopes/GamestonkTerminal#85]
**Describe the bug**
After building a docker image, the application crashes when I try to execute with `docker run`, with the following error:

```
2021-03-03 15:16:41.157332: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-03-03 15:16:41.157405: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
/home/python/.local/lib/python3.6/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0

Welcome to Didier's Gamestonk Terminal

What do you want to do?
   help        help to see this menu again
   quit        to abandon the program

   clear       clear a specific stock ticker from analysis
   load        load a specific stock ticker for analysis
   view        view and load a specific stock ticker for technical analysis

Stock: ?
Market OPEN.

Menus:
   disc        discover trending stocks,         e.g. map, sectors, high short interest
   sen         sentiment of the market,          from: reddit, stocktwits, twitter

> Traceback (most recent call last):
  File "gamestonk_terminal.py", line 328, in <module>
    main()
  File "gamestonk_terminal.py", line 213, in main
    as_input = input('> ')
EOFError: EOF when reading a line
```

**To Reproduce**
Either in Windows 10 or macOS Catalina:
- `docker build -t gamestonkterminal`
- `docker run gamestonkterminal`

**Desktop (please complete the following information):**
 - OS: both macOS Catalina and Windows 10 1909
 - Python version [e.g. 3.6.8]

**Additional context**
GPU: GeForce GTX 1060 with the last Game Ready drivers installed.

**Comment by shadycuz** [comment]
@efontan When running with docker you need to use `docker run -it gamestonkterminal`. The `-it` means "interactive" and "terminal" (I think). 

You can also run `docker-compose run gamestonkterminal`. 

I'm going to close this but if it still doesn't work just reopen. 

🚀 GamestonkTerminal 🌔

**Comment by avocardio** [comment]
Hey, has there been a fix for this? I get the same error.. even after running like @shadycuz proposed.
