### ISSUE TITLE
Install breaks on Ubuntu 16.04.7  with pip 8.1.1

### ISSUE THREAD

**Issue by cphoover** [DidierRLopes/GamestonkTerminal#92]
**Describe the bug**
Install seems to be doing a lot of stuff and then fails unexpectedly with the following error:

```
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vDZpkv/cmdstanpy/
```

**To Reproduce**
pip install -r requirements.txt

**Logs from command**

```
[censored]@development:~/src/GamestonkTerminal$ pip install -r requirements.txt 
The directory '[censored]/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '[censored]/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Ignoring aiohttp: markers u'python_version >= "3.6"' don't match your environment
Ignoring async-timeout: markers u'python_full_version >= "3.5.3" and python_version >= "3.6"' don't match your environment
Ignoring attrs: markers u'python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6"' don't match your environment
Ignoring bpemb: markers u'python_version >= "3.6"' don't match your environment
Ignoring cachetools: markers u'python_version >= "3.5" and python_version < "4.0" and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.6.0")' don't match your environment
Ignoring chardet: markers u'python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version >= "3.6"' don't match your environment
Ignoring click: markers u'python_full_version >= "3.6.0" and python_version >= "3.6"' don't match your environment
Ignoring cloudpickle: markers u'python_version >= "3.6"' don't match your environment
Ignoring convertdate: markers u'python_version >= "3.5"' don't match your environment
Ignoring cycler: markers u'python_version >= "3.6"' don't match your environment
Ignoring cython: markers u'python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" and python_version >= "3.6"' don't match your environment
Ignoring dataclasses: markers u'python_version >= "3.6" and python_version < "3.7" and python_full_version >= "3.6.2"' don't match your environment
Ignoring decorator: markers u'python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.2.0" and python_version >= "3.6"' don't match your environment
Ignoring deprecated: markers u'python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6"' don't match your environment
Ignoring filelock: markers u'python_full_version >= "3.6.0" and python_version >= "3.6"' don't match your environment
Ignoring flair: markers u'python_version >= "3.6"' don't match your environment
Ignoring ftfy: markers u'python_version >= "3.6"' don't match your environment
Ignoring future: markers u'python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" and python_version >= "3.6"' don't match your environment
Ignoring gdown: markers u'python_version >= "3.6"' don't match your environment
Ignoring gensim: markers u'python_version >= "3.6"' don't match your environment
Ignoring google-auth-oauthlib: markers u'python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.2.0" and python_version >= "3.6"' don't match your environment
Ignoring google-auth: markers u'python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6"' don't match your environment
Ignoring hijri-converter: markers u'python_version >= "3.6"' don't match your environment
Ignoring hyperopt: markers u'python_version >= "3.6"' don't match your environment
Ignoring idna-ssl: markers u'python_version < "3.7" and python_version >= "3.6"' don't match your environment
Ignoring idna: markers u'python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.7" or python_version < "3.7" and python_version >= "3.6" and python_full_version >= "3.5.0"' don't match your environment
Ignoring importlib-metadata: markers u'python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.2.0" and python_version >= "3.6" and python_version < "3.8"' don't match your environment
Ignoring inflection: markers u'python_version >= "3.5"' don't match your environment
Ignoring janome: markers u'python_version >= "3.6"' don't match your environment
Ignoring joblib: markers u'python_full_version >= "3.6.0" and python_version >= "3.6"' don't match your environment
Ignoring kiwisolver: markers u'python_version >= "3.6"' don't match your environment
Ignoring konoha: markers u'python_full_version >= "3.6.1" and python_full_version < "4.0.0" and python_version >= "3.6"' don't match your environment
Ignoring langdetect: markers u'python_version >= "3.6"' don't match your environment
Ignoring lxml: markers u'python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version >= "3.6"' don't match your environment
Ignoring markdown: markers u'python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.2.0" and python_version >= "3.6"' don't match your environment
Ignoring matplotlib: markers u'python_version >= "3.6"' don't match your environment
Ignoring more-itertools: markers u'python_version >= "3.5"' don't match your environment
Ignoring mpld3: markers u'python_version >= "3.6"' don't match your environment
Ignoring multidict: markers u'python_version >= "3.6"' don't match your environment
Ignoring networkx: markers u'python_version >= "3.6"' don't match your environment
Ignoring numpy: markers u'python_version >= "3.6" and python_full_version >= "3.6.2" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.2.0" and python_version >= "3.6")' don't match your environment
Ignoring oauthlib: markers u'python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6"' don't match your environment
Ignoring opt-einsum: markers u'python_version >= "3.5"' don't match your environment
Ignoring overrides: markers u'python_full_version >= "3.6.1" and python_full_version < "4.0.0" and python_version >= "3.6"' don't match your environment
Ignoring packaging: markers u'python_full_version >= "3.6.0" and python_version >= "3.6"' don't match your environment
Ignoring pandas: markers u'python_full_version >= "3.6.1"' don't match your environment
Ignoring patsy: markers u'python_version >= "3.6"' don't match your environment
Ignoring pillow: markers u'python_version >= "3.6"' don't match your environment
Ignoring pmdarima: markers u'python_version >= "3.6"' don't match your environment
Ignoring praw: markers u'python_version >= "3.6" and python_version < "4.0"' don't match your environment
Ignoring prawcore: markers u'python_version >= "3.6" and python_version < "4.0"' don't match your environment
Ignoring prettytable: markers u'python_version >= "3.6"' don't match your environment
Ignoring protobuf: markers u'python_full_version >= "3.6.0" and python_version >= "3.6" and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.2.0")' don't match your environment
Ignoring psaw: markers u'python_version >= "3"' don't match your environment
Ignoring pyasn1: markers u'python_version >= "3.5" and python_full_version < "3.0.0" and python_version < "4" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6") or python_version >= "3.5" and python_version < "4" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6") and python_full_version >= "3.6.0"' don't match your environment
Ignoring pymeeus: markers u'python_version >= "3.5"' don't match your environment
Ignoring pyparsing: markers u'python_full_version >= "3.6.0" and python_version >= "3.6"' don't match your environment
Ignoring python-dateutil: markers u'python_full_version >= "3.6.1" and python_version >= "3.5" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" and python_version >= "3.6") and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.3.0") and (python_version >= "2.7" and python_full_version < "3.0.0" and python_version < "4" or python_version >= "2.7" and python_version < "4" and python_full_version >= "3.3.0")' don't match your environment
Ignoring pytz: markers u'python_full_version >= "3.6.1" and python_version >= "3.5" and python_version < "4"' don't match your environment
Ignoring quandl: markers u'python_version >= "3.5"' don't match your environment
Ignoring regex: markers u'python_full_version >= "3.6.0" and python_version >= "3.6"' don't match your environment
Ignoring requests-oauthlib: markers u'python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6"' don't match your environment
Ignoring rsa: markers u'python_version >= "3.5" and python_version < "4" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.6.0" and python_version >= "3.6")' don't match your environment
Ignoring sacremoses: markers u'python_full_version >= "3.6.0" and python_version >= "3.6"' don't match your environment
Ignoring scikit-learn: markers u'python_version >= "3.6"' don't match your environment
Ignoring scipy: markers u'python_version >= "3.6"' don't match your environment
Ignoring segtok: markers u'python_version >= "3.6"' don't match your environment
Ignoring sentencepiece: markers u'python_full_version >= "3.6.0" and python_version >= "3.6"' don't match your environment
Ignoring six: markers u'python_full_version >= "3.6.0" and python_version >= "3.6" and python_version < "4.0" and (python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.3.0" and python_version >= "3.6") and (python_version >= "2.7" and python_full_version < "3.0.0" or python_full_version >= "3.6.0")' don't match your environment
Ignoring smart-open: markers u'python_version >= "3.6"' don't match your environment
Ignoring soupsieve: markers u'python_version >= "3.6"' don't match your environment
Ignoring sqlitedict: markers u'python_version >= "3.6"' don't match your environment
Ignoring statsmodels: markers u'python_version >= "3.6"' don't match your environment
Ignoring tabulate: markers u'python_version >= "3.6"' don't match your environment
Ignoring threadpoolctl: markers u'python_version >= "3.6"' don't match your environment
Ignoring tokenizers: markers u'python_full_version >= "3.6.0" and python_version >= "3.6"' don't match your environment
Ignoring torch: markers u'python_full_version >= "3.6.2" and python_version >= "3.6"' don't match your environment
Ignoring tqdm: markers u'python_full_version >= "3.6.0" and python_version >= "3.6"' don't match your environment
Ignoring transformers: markers u'python_full_version >= "3.6.0" and python_version >= "3.6"' don't match your environment
Ignoring typing-extensions: markers u'python_full_version >= "3.6.2" and python_version >= "3.6" and python_version < "3.8" and (python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.2.0" and python_version >= "3.6" and python_version < "3.8")' don't match your environment
Ignoring update-checker: markers u'python_version >= "3.6" and python_version < "4.0"' don't match your environment
Ignoring urllib3: markers u'python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.5.0" and python_version < "4" and python_version >= "3.6"' don't match your environment
Ignoring wcwidth: markers u'python_version >= "3.6"' don't match your environment
Ignoring websocket-client: markers u'python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "4.0" or python_version >= "3.6" and python_version < "4.0" and python_full_version >= "3.4.0"' don't match your environment
Ignoring wrapt: markers u'python_version >= "3.6" and python_full_version < "3.0.0" or python_full_version >= "3.4.0" and python_version >= "3.6"' don't match your environment
Ignoring yarl: markers u'python_version >= "3.6"' don't match your environment
Ignoring zipp: markers u'python_version >= "3.6" and python_full_version < "3.0.0" and python_version < "3.8" or python_full_version >= "3.2.0" and python_version >= "3.6" and python_version < "3.8"' don't match your environment
Collecting absl-py==0.11.0 (from -r requirements.txt (line 1))
  Downloading [censored]/artifactory/api/pypi/pypi-release/packages/packages/af/88/d97853ec7d4c487a7e3efe379b926b3c4d33fedc5d11d6a2fb6c2ab55646/absl-py-0.11.0.tar.gz (110kB)
    100% |████████████████████████████████| 112kB 8.7MB/s 
Collecting alpha-vantage==2.3.1 (from -r requirements.txt (line 3))
  Downloading  [censored]/artifactory/api/pypi/pypi-release/packages/packages/75/ea/28417504b1d0701626b76e150cf114b958c4b40d44da006303dc6a6dcce3/alpha_vantage-2.3.1.tar.gz
Collecting astunparse==1.6.3 (from -r requirements.txt (line 4))
  Downloading [censored]/artifactory/api/pypi/pypi-release/packages/packages/2b/03/13dde6512ad7b4557eb792fbcf0c653af6076b81e5941d36ec61f7ce6028/astunparse-1.6.3-py2.py3-none-any.whl
Collecting beautifulsoup4==4.9.3 (from -r requirements.txt (line 7))
  Downloading  [censored]/artifactory/api/pypi/pypi-release/packages/packages/1c/d9/8c507915ff962b9e854b477b203c171074f59cce9465dac9f71c2b57ebd6/beautifulsoup4-4.9.3-py2-none-any.whl (115kB)
    100% |████████████████████████████████| 122kB 47.4MB/s 
Collecting bs4==0.0.1 (from -r requirements.txt (line 9))
  Downloading  [censored]/artifactory/api/pypi/pypi-release/packages/packages/10/ed/7e8b97591f6f456174139ec089c769f89a94a1a4025fe967691de971f314/bs4-0.0.1.tar.gz
Collecting certifi==2020.12.5 (from -r requirements.txt (line 11))
  Downloading  [censored]/artifactory/api/pypi/pypi-release/packages/packages/5e/a0/5f06e1e1d463903cf0c0eebeb751791119ed7a4b3737fdc9a77f1cdfb51f/certifi-2020.12.5-py2.py3-none-any.whl (147kB)
    100% |████████████████████████████████| 153kB 37.8MB/s 
Collecting cmdstanpy==0.4.0 (from -r requirements.txt (line 15))
  Downloading  [censored]/artifactory/api/pypi/pypi-release/packages/packages/7d/34/5b35f74836b5cb355d9b5046091e910389d834fef4e8577161ae7d5e048f/cmdstanpy-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vDZpkv/cmdstanpy/setup.py", line 8
        def readme_contents() -> str:
                              ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vDZpkv/cmdstanpy/

```

**Comment by shadycuz** [comment]
@cphoover Tesnorflow only supports `pip` >= 2.19 or something like that. 

Could you please update the pip version and retry?

It also seems you are on a python version lower than `3.6`:
`Ignoring aiohttp: markers u'python_version >= "3.6"' don't match your environment`

You will need at least python `3.6` to run GamestonkTerminal. Since python 3.5 is EOL and 3.6 is soon to be EOL. I recommended you upgrade to at least `3.7`. 

You can find instructions [here](https://realpython.com/intro-to-pyenv/)

**Comment by gmerrall** [comment]
That pip version number seems awfully low even for Xenial Can you please run 'pip -V'

Note that Xenial only has Python 3.5.  If you want to run gamestonk terminal consider installing a [3.6 backport](http://devopspy.com/python/install-python-3-6-ubuntu-lts/) or spinning up something like Vagrant or Docker.

**Comment by aia** [comment]
We have made several changes to the installation. Please take a look at the latest changes.

Continuous Integration for Ubuntu is passing - https://github.com/DidierRLopes/GamestonkTerminal/runs/2051726427.
